version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: referrals
      POSTGRES_USER: referralsuser
      POSTGRES_PASSWORD: referralspassword
    ports:
      - "5432:5432"

    restart: always

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"

    ports:
      - "8002:8002"

    environment:
      POSTGRES_DB: referrals
      POSTGRES_USER: referralsuser
      POSTGRES_PASSWORD: referralspassword

    depends_on:
      - db

    restart: always