# Generated by Django 4.2.4 on 2023-08-26 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('used_foreign_invite', models.BooleanField(default=False)),
                ('authorization_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('referral_users', models.ManyToManyField(blank=True, to='referrals.userprofile')),
            ],
        ),
    ]
